// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRNJoH-V7kVeG0wYarAxQ3brRP-h450aE',
    appId: '1:78549410636:web:17a8ad55c75fb1f149e5e9',
    messagingSenderId: '78549410636',
    projectId: 'elcorazon-a3df0',
    authDomain: 'elcorazon-a3df0.firebaseapp.com',
    storageBucket: 'elcorazon-a3df0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3sOcim7KjLCAVGkJPaWYkEmbcrozjWws',
    appId: '1:78549410636:android:d3e11784dc8ec84e49e5e9',
    messagingSenderId: '78549410636',
    projectId: 'elcorazon-a3df0',
    storageBucket: 'elcorazon-a3df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_IuJX_LiOJiE7SnbhIDvPxdir0s-9X-0',
    appId: '1:78549410636:ios:92957e9be87faa7a49e5e9',
    messagingSenderId: '78549410636',
    projectId: 'elcorazon-a3df0',
    storageBucket: 'elcorazon-a3df0.firebasestorage.app',
    iosBundleId: 'com.example.elcoraDely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_IuJX_LiOJiE7SnbhIDvPxdir0s-9X-0',
    appId: '1:78549410636:ios:92957e9be87faa7a49e5e9',
    messagingSenderId: '78549410636',
    projectId: 'elcorazon-a3df0',
    storageBucket: 'elcorazon-a3df0.firebasestorage.app',
    iosBundleId: 'com.example.elcoraDely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRNJoH-V7kVeG0wYarAxQ3brRP-h450aE',
    appId: '1:78549410636:web:7d440a99764dc28e49e5e9',
    messagingSenderId: '78549410636',
    projectId: 'elcorazon-a3df0',
    authDomain: 'elcorazon-a3df0.firebaseapp.com',
    storageBucket: 'elcorazon-a3df0.firebasestorage.app',
  );

}